SET SCHEMA = 'BFIS';
CREATE TABLE  BFIS.TBFIS25(
DIS_ID varchar(50) not null,
JSON_DATE varchar(500),
CREATE_TIME varchar(30),
SUCCESS_STATUS varchar(4),
PRIMARY KEY (DIS_ID)
)
IN "BFIS"
INDEX IN "BFISINDEX"
lONG IN "BFISLONG";
GRANT SELECT ON TABLE "BFIS"."TBFIS25" TO USER "DWUSER";
GRANT SELECT ON TABLE "BFIS"."TBFIS25" TO USER "BSFCVIEW";
COMMENT ON TABLE TBFIS25
IS
    '宝利通提现推送表';
COMMENT ON COLUMN TBFIS25.DIS_ID
IS
    '编号';
COMMENT ON COLUMN TBFIS25.JSON_DATE
IS
    'JSON数据';
COMMENT ON COLUMN TBFIS25.CREATE_TIME
IS
    '创建时间';
COMMENT ON COLUMN TBFIS25.SUCCESS_STATUS
IS
   '发送成功状态  0-成功；1-失败';